// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

//#include "boards/pico.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:

#define PLL_SYS_POSTDIV1 4
#define PLL_SYS_POSTDIV2 2
#define SYS_CLK_KHZ 200000
#define PLL_SYS_VCO_FREQ_KHZ 1600000

#define NDEBUG 1
#define PICO_USE_STACK_GUARDS 1
#define PICO_REMOVE_PN532_DEV 1 // Временно отключить инициализацию и использование PN532
#define PICO_ENTER_USB_BOOT_ON_EXIT 1

